# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale	 	   : "en-US"
title	 	   : Brian Bingham's Github Pages
email	 	   : briansbingham@gmail.com
description	   : >- # this means to ignore newlines until "baseurl:"
  Robotics examples, tutorials and how-tos - typically using ROS and Gazebo.
baseurl	   	   : "" # the subpath of your site, e.g. /blog
url		   : "https://bsb808.github.io/"

# Social Sharing
twitter:
  username	   : "bbing"
twitter_username   : bbing
github_username	   :  bbing808
search: true
# Build settings

permalink: /:categories/:title/
paginate: 7 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap
  
author:
  name   : "Brian Bingham"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Robotics and software."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:briansbingham@gmail.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bbing"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bsb808"

#footer:
#  links:
#    - label: "Email"
#      icon: "fas fa-fw fa-envelope-square"
#      url: mailto:briansbingham@gmail.com
##    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/bbing"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/bsb808"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: false
      mathjax: true	
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
